name: Tests

on: [push]

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.3', '8.4']
        steps:
            - name: Setup PHP with PECL extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Unit tests
              run: composer test:unit
